version: '3.4'

services:
  gogs-server:
    image: gogs/gogs
    networks:
      - traefik-net
    volumes:
      - data:/data
    environment:
      - "RUN_CROND=true"
    deploy:
      labels:
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:gogs.container.se.lab.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

volumes:
  data:
    driver: rexray/scaleio
    driver_opts:
      size: 100

networks:
  traefik-net:
    external: true
